1. pip install django
2. pip freeze
3. django-admin startproject YourProjectName
4. cd YourProjectName
5. dir

To run Server:
6. python manage.py runserver

=================
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
January 08, 2022 - 10:26:57
Django version 4.0.1, using settings 'cmbprj.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Error: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

=======================


If get any Error to Run Server use the following command(Step: 7) & Try again (Step: 6):
7. python manage.py migrate


If found Error on port 8080 change it to any other port number eg. 9000
8. python manage.py runserver 9000



9. From Browser type: http://127.0.0.1:9000/
*** Here use the port number as per you installed.


List of Error have found during installation Django
====================

Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying sessions.0001_initial... OK

D:\PythonWorks\Day14 2022-01-08 DataBase\cmbprj>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 08, 2022 - 10:28:01
Django version 4.0.1, using settings 'cmbprj.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Error: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

D:\PythonWorks\Day14 2022-01-08 DataBase\cmbprj>python manage.py runserver 9000
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 08, 2022 - 10:28:34
Django version 4.0.1, using settings 'cmbprj.settings'
Starting development server at http://127.0.0.1:9000/
Quit the server with CTRL-BREAK.
[08/Jan/2022 10:29:19] "GET / HTTP/1.1" 200 10697
[08/Jan/2022 10:29:19] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[08/Jan/2022 10:29:19] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[08/Jan/2022 10:29:19] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[08/Jan/2022 10:29:19] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
Not Found: /favicon.ico
[08/Jan/2022 10:29:19] "GET /favicon.ico HTTP/1.1" 404 2110



